### ISSUE TITLE
Issue with bootstrap version used.

### ISSUE THREAD

**Issue by choakumndi** [app-generator/django-pixel-bootstrap-uikit#1]
I noted a bug caused by the bootstrap version (4.4.1) that is used in the uikit. The collapsed menu does not display.(see screenshot)

![image](https://user-images.githubusercontent.com/5228299/99916309-c2239700-2d09-11eb-980b-415bb5ec3394.png)

However, I notice when I changed the bootstrap version to 4.3.1, I don't see the error.(see screenshot below)

![image](https://user-images.githubusercontent.com/5228299/99916489-bc7a8100-2d0a-11eb-9da2-772a9b2722fd.png)

Please could it be fixed, I guess it may be the same reason why the other vendor plugins seem not to function well.

**Comment by pejacqueline** [comment]
Hi!
I have the same problem. I'm a novice developer, could you quickly explain me how to upgrade to version 4.3.1 of bootstrap please?
Thanks
Have a nice day.

**Comment by app-generator** [comment]
Hello Guys,
Soon we will update this starter to the latest version of Pixel (v.3.1.2)

https://demo.themesberg.com/pixel-lite/index.html

Here is the public repo used by AppSeed to generate the starter.

https://github.com/themesberg/pixel-bootstrap-ui-kit

P.S. Being requested by more than one developer, we will provide sooner the upgrade (probably in the next 4h)

**Comment by app-generator** [comment]
Hello,

Thank you for using our products.
The fastest way is to use the CDN minified versions in the master pages.
You can find the paths by accessing this page:

https://getbootstrap.com/docs/4.3/getting-started/download/

Note: This version is untested by us or Themesberg. Make sure you
double-check the effects before putting in production.


- AppSeed Support

**Comment by pejacqueline** [comment]
Thank you very much, it seems to work perfectly! 
Have a great day!

**Comment by app-generator** [comment]
P.S. Pixel Lite the latest version is now available in Jinja/Flask - our intermediate format.

https://github.com/app-generator/jinja-template-pixel-uikit

Soon Flask/Django starters will be generated on top.

**Comment by app-generator** [comment]
Patched in release [v1.0.1](https://github.com/app-generator/django-pixel-bootstrap-uikit/releases/tag/v1.0.1-rc1)
