### ISSUE TITLE
how to run using Flask on mac os x

### ISSUE THREAD

**Issue by lillois59** [app-generator/django-pixel-bootstrap-uikit#2]
Hi all,

Id like to try the freelancer template for my personal work im new in web-dev id like to know how I can run django-pixel using flask
I mean I know how to run django app using manage.py but im confuse with flash. Also im trying to registrer like in step :
Start the app via flask run
Access the registration page and create a new user:
http://127.0.0.1:8000/register/

Im confuse because I get the same page using manage.py but not working I mean I fell all field but the same registrer page appear again. So how I can run "flask run ..."

(env)sofiane-MBP:desktop Apple$ cd django-pixel
(env)sofiane-MBP:django-pixel Apple$ flask run
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Could not locate a Flask application. Use the 'flask --app' option, 'FLASK_APP' environment variable, or a 'wsgi.py' or 'app.py' file in the current directory.

**Comment by app-generator** [comment]
Hello @lillois59 

Thank you for using our products. 

Being a Django project, Flask cannot be involved in the process. 
In order to use the project please follow up the instructions as presented in the README. 

If you prefer to use Flask, instead of Django, please access this project (also free): 

https://github.com/app-generator/flask-pixel

**Comment by lillois59** [comment]
Hi @app-generator thanks for your support and quick response no really thanks you.
This morning following your advise I get something I mean Its work after registration and login. 
I have some question please guys, I wanna to use just the freelancer landing page (I already change this morning some content photo text etctera) but I need to remove all some link and also more important I want to that no one can access to any page only the freelancer page please (follow me in LinkedIn* if you want */lillois)

final wanted result on web :
mydomaine.com (using your template)
... mydomaine.com/freelancer-page.html (your template only)

merci x thanks a lots by advance
